name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup
        run: make setup

      - name: Build project
        run: make build

      - name: Checkstyle Main
        run: make checkstyleMain

      - name: Checkstyle Test
        run: make checkstyleTest

      - name: Tests
        run: make test